spring:
  datasource:
    url: jdbc:tc:postgresql:13.3:///testdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: testuser
    password: testpassword

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop